<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/progresse/_create.blade.php" was generated by ProBot AI.
* Date: 5/22/2025 11:23:46 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Progresse')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('progresses.index')}}">Manage</a>
<form action="{{route('progresses.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="module_id" class="col-sm-2 col-form-label">Module</label>
	<div class="col-sm-10">
		<select class="form-control" name="module_id" id="module_id">
			@foreach($modules as $module)
				<option value="{{$module->id}}">{{$module->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="project_id" class="col-sm-2 col-form-label">Project</label>
	<div class="col-sm-10">
		<select class="form-control" name="project_id" id="project_id">
			@foreach($projects as $project)
				<option value="{{$project->id}}">{{$project->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="percent" class="col-sm-2 col-form-label">Percent</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="percent" id="percent" placeholder="Percent">
	</div>
</div>
<div class="row mb-3">
	<label for="review" class="col-sm-2 col-form-label">Review</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="review" id="review" placeholder="Review">
	</div>
</div>
<div class="row mb-3">
	<label for="status" class="col-sm-2 col-form-label">Status</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="status" id="status" placeholder="Status">
	</div>
</div>
<div class="row mb-3">
	<label for="expected_completion_date" class="col-sm-2 col-form-label">Expected Completion Date</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="expected_completion_date" id="expected_completion_date" placeholder="Expected Completion Date">
	</div>
</div>
<div class="row mb-3">
	<label for="actual_completion_date" class="col-sm-2 col-form-label">Actual Completion Date</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="actual_completion_date" id="actual_completion_date" placeholder="Actual Completion Date">
	</div>
</div>
<div class="row mb-3">
	<label for="remark" class="col-sm-2 col-form-label">Remark</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="remark" id="remark" placeholder="Remark">
	</div>
</div>
<div class="row mb-3">
	<label for="updated_by" class="col-sm-2 col-form-label">Updated By</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="updated_by" id="updated_by" placeholder="Updated By"></textarea>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
