<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/progresse/_index.blade.php" was generated by ProBot AI.
* Date: 5/22/2025 11:23:46 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Progresse')
@section('style')


@endsection
@section('page')
<a href="{{route('progresses.create')}}">New Progresse</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Module Id</th>
			<th>Project Id</th>
			<th>Percent</th>
			<th>Review</th>
			<th>Status</th>
			<th>Expected Completion Date</th>
			<th>Actual Completion Date</th>
			<th>Remark</th>
			<th>Updated By</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($progresses as $progresse)
		<tr>
			<td>{{$progresse->id}}</td>
			<td>{{$progresse->module_id}}</td>
			<td>{{$progresse->project_id}}</td>
			<td>{{$progresse->percent}}</td>
			<td>{{$progresse->review}}</td>
			<td>{{$progresse->status}}</td>
			<td>{{$progresse->expected_completion_date}}</td>
			<td>{{$progresse->actual_completion_date}}</td>
			<td>{{$progresse->remark}}</td>
			<td>{{$progresse->updated_by}}</td>
			<td>{{$progresse->Created_at}}</td>
			<td>{{$progresse->updated_at}}</td>

			<td>
			<form action = "{{route('progresses.destroy',$progresse->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('progresses.show',$progresse->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('progresses.edit',$progresse->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
