<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/progresse/_show.blade.php" was generated by ProBot AI.
* Date: 5/22/2025 11:23:46 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Progresse')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('progresses.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$progresse->id}}</td></tr>
		<tr><th>Module Id</th><td>{{$progresse->module_id}}</td></tr>
		<tr><th>Project Id</th><td>{{$progresse->project_id}}</td></tr>
		<tr><th>Percent</th><td>{{$progresse->percent}}</td></tr>
		<tr><th>Review</th><td>{{$progresse->review}}</td></tr>
		<tr><th>Status</th><td>{{$progresse->status}}</td></tr>
		<tr><th>Expected Completion Date</th><td>{{$progresse->expected_completion_date}}</td></tr>
		<tr><th>Actual Completion Date</th><td>{{$progresse->actual_completion_date}}</td></tr>
		<tr><th>Remark</th><td>{{$progresse->remark}}</td></tr>
		<tr><th>Updated By</th><td>{{$progresse->updated_by}}</td></tr>
		<tr><th>Created At</th><td>{{$progresse->Created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$progresse->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
