<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderdetail/_create.blade.php" was generated by ProBot AI.
* Date: 5/11/2025 9:23:48 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Create OrderDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orderdetails.index')}}">Manage</a>
<form action="{{route('orderdetails.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="order_id" class="col-sm-2 col-form-label">Order</label>
	<div class="col-sm-10">
		<select class="form-control" name="order_id" id="order_id">
			@foreach($orders as $order)
				<option value="{{$order->id}}">{{$order->id}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="property_id" class="col-sm-2 col-form-label">Property</label>
	<div class="col-sm-10">
		<select class="form-control" name="property_id" id="property_id">
			@foreach($propertys as $property)
				<option value="{{$property->id}}">{{$property->title}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="flat_no" class="col-sm-2 col-form-label">Flat No</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="flat_no" id="flat_no" placeholder="Flat No">
	</div>
</div>
<div class="row mb-3">
	<label for="amount" class="col-sm-2 col-form-label">Amount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="amount" id="amount" placeholder="Amount">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
