<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/stockadjustmenttype/_show.blade.php" was generated by ProBot AI.
* Date: 5/10/2025 12:00:26 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Show StockAdjustmentType')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('stockadjustmenttypes.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$stockadjustmenttype->id}}</td></tr>
		<tr><th>Name</th><td>{{$stockadjustmenttype->name}}</td></tr>
		<tr><th>Factor</th><td>{{$stockadjustmenttype->factor}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
