<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_create.blade.php" was generated by ProBot AI.
* Date: 5/12/2025 11:33:02 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Create Product')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('products.index')}}">Manage</a>
<form action="{{route('products.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="offer_price" class="col-sm-2 col-form-label">Offer Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="offer_price" id="offer_price" placeholder="Offer Price">
	</div>
</div>
<div class="row mb-3">
	<label for="manufacturer_id" class="col-sm-2 col-form-label">Manufacturer</label>
	<div class="col-sm-10">
		<select class="form-control" name="manufacturer_id" id="manufacturer_id">
			@foreach($manufacturers as $manufacturer)
				<option value="{{$manufacturer->id}}">{{$manufacturer->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="regular_price" class="col-sm-2 col-form-label">Regular Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="regular_price" id="regular_price" placeholder="Regular Price">
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="description" id="description" placeholder="Description"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="product_category_id" class="col-sm-2 col-form-label">Product_Category</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_category_id" id="product_category_id">
			@foreach($product_categorys as $product_category)
				<option value="{{$product_category->id}}">{{$product_category->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="weight" class="col-sm-2 col-form-label">Weight</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="weight" id="weight" placeholder="Weight"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="stock_qty" class="col-sm-2 col-form-label">Stock Qty</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="stock_qty" id="stock_qty" placeholder="Stock Qty">
	</div>
</div>
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
		<input type = "file" class="form-control" name="photo" id="photo" placeholder="Photo">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
