<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_index.blade.php" was generated by ProBot AI.
* Date: 5/12/2025 11:33:02 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Manage Product')
@section('style')


@endsection
@section('page')
<a href="{{route('products.create')}}">New Product</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Offer Price</th>
			<th>Manufacturer Id</th>
			<th>Regular Price</th>
			<th>Description</th>
			<th>Product Category Id</th>
			<!-- <th>Is Brand</th> -->
			<th>Weight</th>
			<!-- <th>Created At</th>
			<th>Updated At</th> -->
			<th>Stock Qty</th>
			<th>Photo</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($products as $product)
		<tr>
			<td>{{$product->id}}</td>
			<td>{{$product->name}}</td>
			<td>{{$product->offer_price}}</td>
			<td>{{$product->manufacturer_id}}</td>
			<td>{{$product->regular_price}}</td>
			<td>{{$product->description}}</td>
			<td>{{$product->product_category_id}}</td>
			<!-- <td>{{$product->is_brand}}</td> -->
			<td>{{$product->weight}}</td>
			<!-- <td>{{$product->created_at}}</td>
			<td>{{$product->updated_at}}</td> -->
			<td>{{$product->stock_qty}}</td>
			<td><img src="{{asset('img/'.$product->photo)}}" width="100" /></td>

			<td>
			<form action = "{{route('products.destroy',$product->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('products.show',$product->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('products.edit',$product->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
