<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_show.blade.php" was generated by ProBot AI.
* Date: 5/12/2025 11:33:02 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Show Product')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('products.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$product->id}}</td></tr>
		<tr><th>Name</th><td>{{$product->name}}</td></tr>
		<tr><th>Offer Price</th><td>{{$product->offer_price}}</td></tr>
		<tr><th>Manufacturer Id</th><td>{{$product->manufacturer_id}}</td></tr>
		<tr><th>Regular Price</th><td>{{$product->regular_price}}</td></tr>
		<tr><th>Description</th><td>{{$product->description}}</td></tr>
		<tr><th>Product Category Id</th><td>{{$product->product_category_id}}</td></tr>
		<tr><th>Is Brand</th><td>{{$product->is_brand}}</td></tr>
		<tr><th>Weight</th><td>{{$product->weight}}</td></tr>
		<tr><th>Created At</th><td>{{$product->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$product->updated_at}}</td></tr>
		<tr><th>Stock Qty</th><td>{{$product->stock_qty}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$product->photo)}}" width="100" /></td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
