<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\AgentController;
use App\Http\Controllers\PropertyController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ContractorController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\PropertyStatusController;
use App\Http\Controllers\Authcontroller;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\ProductUnitController;
use App\Http\Controllers\ProductSectionController;
use App\Http\Controllers\ProductTypeController;
use App\Http\Controllers\ManufacturerController;
use App\Http\Controllers\PurchaseDetailController;
use App\Http\Controllers\UomController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\TransactionTypeController;
use App\Http\Controllers\WarehouseController;
use App\Http\Controllers\StockAdjustmentController;
use App\Http\Controllers\StockAdjustmentDetailController;
use App\Http\Controllers\StockAdjustmentTypeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderDetailController;
use App\Http\Controllers\MoneyReceiptController;
use App\Http\Controllers\MoneyReceiptDetailController;
use App\Http\Controllers\StockTransperController;
use App\Http\Controllers\StockTransperDetailController;
use App\Http\Controllers\ProjectTypeController;
use App\Http\Controllers\ProjectModuleController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\ProjectPersonController;
use App\Http\Controllers\PersonController;
use App\Http\Controllers\ProjectCostingController;
use App\Http\Controllers\ProjectStatuseController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ProgresseController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\InvoiceDetailController;
use App\Http\Controllers\AdminController;


Route::get('/', [Authcontroller::class, 'login'])->name('login');
Route::post('login', [Authcontroller::class, 'Authlogin']);
Route::post('logout', [Authcontroller::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [HomeController::class, 'index']);
   
    Route::resource('propertys', PropertyController::class);
    Route::resource('categorys', CategoryController::class);
    Route::resource('agents', AgentController::class);
    Route::resource('customers', CustomerController::class);
    Route::resource('contractors', ContractorController::class);
    Route::resource('projects', ProjectController::class);
    Route::resource('propertystatuses', PropertyStatusController::class);
    Route::resource('purchases', PurchaseController::class);
    Route::resource('vendors', VendorController::class);
    Route::resource('status', StatusController::class);
    Route::resource('products', ProductController::class);
    Route::resource('productcategorys', ProductCategoryController::class);
    Route::resource('sections', SectionController::class);
    Route::resource('productunits', ProductUnitController::class);
    Route::resource('productsections', ProductSectionController::class);
    Route::resource('producttypes', ProductTypeController::class);
    Route::resource('manufacturers', ManufacturerController::class);
    Route::resource('purchasedetails', PurchaseDetailController::class);
    Route::resource('uoms', UomController::class);
    Route::resource('stocks', StockController::class);
    Route::get("/balances",[StockController::class,'balance']);
    Route::resource('transactiontypes', TransactionTypeController::class);
    Route::resource('warehouses', WarehouseController::class);
    Route::resource('stockadjustments', StockAdjustmentController::class);
    Route::resource('stockadjustmentdetails', StockAdjustmentDetailController::class);
    Route::resource('stockadjustmenttypes', StockAdjustmentTypeController::class);
    Route::resource('users', UserController::class);
    Route::resource('orders', OrderController::class);
    Route::resource('orderdetails', OrderDetailController::class);
    Route::resource('moneyreceipts', MoneyReceiptController::class);
    Route::resource('moneyreceiptdetails', MoneyReceiptDetailController::class);
    Route::resource('stocktranspers', StockTransperController::class);
    Route::resource('stocktransperdetails', StockTransperDetailController::class);
    Route::resource('projecttypes', ProjectTypeController::class);
    Route::resource('projectstatuses', ProjectStatuseController::class);
    Route::resource('projectmodules', ProjectModuleController::class);
    Route::resource('modules', ModuleController::class);
    Route::resource('projectpersons', ProjectPersonController::class);
    Route::resource('persons', PersonController::class);
    Route::resource('projectcostings', ProjectCostingController::class);
    Route::resource('companys', CompanyController::class);
    Route::resource('progresses', ProgresseController::class);
    Route::resource('invoices', InvoiceController::class);
    Route::resource('invoicedetails', InvoiceDetailController::class);
    Route::get('/stock-issue/create', [App\Http\Controllers\StockController::class, 'createIssue'])->name('stock.issue.create');
    Route::post('/stock-issue/store', [App\Http\Controllers\StockController::class, 'storeIssue'])->name('stock.issue.store');
    Route::get('/stock-issue/manage', [App\Http\Controllers\StockController::class, 'manageIssue'])->name('stock.issue.manage');
});
