<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/moneyreceipt/_create.blade.php" was generated by ProBot AI.
* Date: 5/12/2025 12:31:28 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Create MoneyReceipt')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('moneyreceipts.index')}}">Manage</a>
<form action="{{route('moneyreceipts.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
	<div class="col-sm-10">
		<select class="form-control" name="customer_id" id="customer_id">
			@foreach($customers as $customer)
				<option value="{{$customer->id}}">{{$customer->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="remark" class="col-sm-2 col-form-label">Remark</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="remark" id="remark" placeholder="Remark"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="receipt_total" class="col-sm-2 col-form-label">Receipt Total</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="receipt_total" id="receipt_total" placeholder="Receipt Total">
	</div>
</div>
<div class="row mb-3">
	<label for="discount" class="col-sm-2 col-form-label">Discount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount" id="discount" placeholder="Discount">
	</div>
</div>
<div class="row mb-3">
	<label for="vat" class="col-sm-2 col-form-label">Vat</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="vat" id="vat" placeholder="Vat">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
