<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/project/_index.blade.php" was generated by ProBot AI.
* Date: 5/6/2025 12:39:42 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Manage Project')
@section('style')


@endsection
@section('page')
<a href="{{route('projects.create')}}">New Project</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Photo</th>
			<th>Name</th>
			<th>Description</th>
			<th>Status</th>
			<th>Start Date</th>
			<th>End Date</th>
			<th>Contractor</th>
			<th>Budget</th>
			<th>Totat Cost</th>
			<!-- <th>Created At</th>
			<th>Updated At</th> -->

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		@foreach($projects as $project)
		<tr>
			<td>{{$project->id}}</td>
			<td><img src="{{asset('img/'.$project->photo)}}" width="100" /></td>
			<td>{{$project->name}}</td>
			<td>{{$project->description}}</td>
			<td>{{ $project->status->name ?? 'N/A' }}</td>
			<td>{{$project->start_date}}</td>
			<td>{{$project->end_date}}</td>
			<td>{{ $project->contractor->name ?? 'N/A' }}</td>
			<td>{{$project->budget}}</td>
			<td>{{$project->totat_cost}}</td>
			<!-- <td>{{$project->created_at}}</td>
			<td>{{$project->updated_at}}</td> -->
			<td>
				<form action="{{route('projects.destroy',$project->id)}}" method="post">
					<a class='btn btn-primary' href="{{route('projects.show',$project->id)}}">View</a>
					<a class='btn btn-success' href="{{route('projects.edit',$project->id)}}"> Edit </a>
					@method('DELETE')
					@csrf
					<input type="submit" class="btn btn-danger" name="delete" value="Delete" />
				</form>
			</td>
		</tr>
		@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection