<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/project/_show.blade.php" was generated by ProBot AI.
* Date: 5/6/2025 12:39:42 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Show Project')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('projects.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$project->id}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$project->photo)}}" width="100" /></td></tr>
		<tr><th>Name</th><td>{{$project->name}}</td></tr>
		<tr><th>Description</th><td>{{$project->description}}</td></tr>
		<tr><th>Status Id</th><td>{{$project->status_id}}</td></tr>
		<tr><th>Start Date</th><td>{{$project->start_date}}</td></tr>
		<tr><th>End Date</th><td>{{$project->end_date}}</td></tr>
		<tr><th>Contractor Id</th><td>{{$project->contractor_id}}</td></tr>
		<tr><th>Budget</th><td>{{$project->budget}}</td></tr>
		<tr><th>Totat Cost</th><td>{{$project->totat_cost}}</td></tr>
		<tr><th>Created At</th><td>{{$project->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$project->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
