<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/academyteacher/_index.blade.php" was generated by ProBot AI.
* Date: 4/27/2025 11:36:18 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Manage AcademyTeacher')
@section('style')


@endsection
@section('page')

<a href="{{route('academyteachers.create')}}">New AcademyTeacher</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Contact No</th>
			<th>Position</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($academyteachers as $academyteacher)
		<tr>
			<td>{{$academyteacher->id}}</td>
			<td>{{$academyteacher->name}}</td>
			<td>{{$academyteacher->contact_no}}</td>
			<td>{{$academyteacher->position}}</td>

			<td>
			<form action = "{{route('academyteachers.destroy',$academyteacher->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('academyteachers.show',$academyteacher->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('academyteachers.edit',$academyteacher->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
