<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/academyteacher/_show.blade.php" was generated by ProBot AI.
* Date: 4/27/2025 11:36:19 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Show AcademyTeacher')
@section('style')


@endsection
@section('page')


<a class='btn btn-success' href="{{route('academyteachers.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$academyteacher->id}}</td></tr>
		<tr><th>Name</th><td>{{$academyteacher->name}}</td></tr>
		<tr><th>Contact No</th><td>{{$academyteacher->contact_no}}</td></tr>
		<tr><th>Position</th><td>{{$academyteacher->position}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
