<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/contractor/_edit.blade.php" was generated by ProBot AI.
* Date: 5/5/2025 12:33:02 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Edit Contractor')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('contractors.index')}}">Manage</a>
<form action="{{route('contractors.update',$contractor)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
		<input type = "file" class="form-control" name="photo"  id="photo" placeholder="Photo">
	</div>
</div>
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$contractor->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="contact_info" class="col-sm-2 col-form-label">Contact Info</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="contact_info" value="{{$contractor->contact_info}}" id="contact_info" placeholder="Contact Info">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
