<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasedetail/_index.blade.php" was generated by ProBot AI.
* Date: 5/8/2025 11:31:46 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Manage PurchaseDetail')
@section('style')


@endsection
@section('page')
<a href="{{route('purchasedetails.create')}}">New PurchaseDetail</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>#</th>
			<th>Warehouse</th>
			<th>Product</th>
			<th>Qty</th>
			<th>Price</th>
			<!-- <th>Vat</th>
			<th>Discount</th> -->
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($purchasedetails as $purchasedetail)
		<tr>
			<td>{{$purchasedetail->id}}</td>
			<td>{{$purchasedetail->purchase->shipping_address}}</td>
		    <td>{{ $purchasedetail->product->name ?? 'N/A' }}</td>
			<td>{{$purchasedetail->qty}}</td>
			<td>{{$purchasedetail->price}}</td>
			<!-- <td>{{$purchasedetail->vat}}</td>
			<td>{{$purchasedetail->discount}}</td> -->
			<td>{{$purchasedetail->created_at}}</td>
			<td>{{$purchasedetail->updated_at}}</td>

			<td>
			<form action = "{{route('purchasedetails.destroy',$purchasedetail->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('purchasedetails.show',$purchasedetail->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('purchasedetails.edit',$purchasedetail->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection

<!-- @foreach ($purchasedetails as $detail)
    <tr>
        <td>{{ $detail->id }}</td>
        <td>{{ $detail->purchase->invoice_number ?? 'N/A' }}</td>
        <td>{{ $detail->product->name ?? 'N/A' }}</td>
        <td>{{ $detail->qty }}</td>
        <td>{{ $detail->price }}</td>
    </tr>
@endforeach -->
