<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/statu/_show.blade.php" was generated by ProBot AI.
* Date: 5/8/2025 11:32:17 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Show Statu')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('status.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$statu->id}}</td></tr>
		<tr><th>Name</th><td>{{$statu->name}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
