<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/transactiontype/_show.blade.php" was generated by ProBot AI.
* Date: 5/10/2025 12:00:51 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')

@section('title','Show TransactionType')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('transactiontypes.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$transactiontype->id}}</td></tr>
		<tr><th>Name</th><td>{{$transactiontype->name}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
