<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/producttype/_show.blade.php" was generated by ProBot AI.
* Date: 5/9/2025 11:12:15 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Show ProductType')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('producttypes.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$producttype->id}}</td></tr>
		<tr><th>Name</th><td>{{$producttype->name}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
