<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/manufacturer/_show.blade.php" was generated by ProBot AI.
* Date: 5/8/2025 11:34:31 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.master')
@section('title','Show Manufacturer')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('manufacturers.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$manufacturer->id}}</td></tr>
		<tr><th>Name</th><td>{{$manufacturer->name}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
